task: textvqa_valglob
test_split: validation
fewshot_split: train
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
dataset_path: lmms-lab/textvqa
output_type: generate_until
doc_to_visual: !function utils.textvqa_doc_to_visual
doc_to_text: !function utils.textvqa_doc_to_text
doc_to_target: "answers"
process_results: !function utils.textvqa_process_results
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
    ocr: false
  qwen_vl:
    pre_prompt: ""
    post_prompt: ""
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml