dataset_path: lmms-lab/ai2d
task: "ai2dglob"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.ai2d_doc_to_visual
doc_to_text: !function utils.ai2d_doc_to_text
doc_to_target: !function utils.ai2d_doc_to_target
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0

model_specific_prompt_kwargs:
  default:
    prompt_format: mcq
    pre_prompt: ""
    post_prompt: ""
  # qwen formulate ai2d as question answering instead of mcq
  qwen_vl:
    prompt_format: qa
    pre_prompt: ""
    post_prompt: ""

model_specific_target_kwargs:
  default: "mcq"
  qwen_vl: "qa"

model_specific_processing_kwargs:
  default: "mcq"
  qwen_vl: "qa"

process_results: !function utils.ai2d_process_results