dataset_path: lmms-lab/ScienceQA
dataset_name: ScienceQA-IMG
task: "scienceqaglob"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.sqa_doc_to_visual
doc_to_text: !function utils.sqa_doc_to_text
doc_to_target: !function utils.sqa_doc_to_target
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
fewshot_split: validation
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.sqa_process_results
metadata:
  - version: 0.0

model_specific_prompt_kwargs:
  default:
    format: default
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    format: qwen_vl
  
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original
  
