dataset_path: HuggingFaceM4/A-OKVQA
test_split: validation
fewshot_split: train
task: "aok_vqaglob"
output_type: generate_until
doc_to_visual: !function utils.aok_vqa_doc_to_visual
doc_to_text: !function utils.aok_vqa_doc_to_text
doc_to_target: !function utils.aok_vqa_doc_to_target
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.aok_vqa_process_results
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  default:
    format: default
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    format: qwen_vl
