task: "infovqa_valglob"
test_split: validation
output_type: generate_until
process_results: !function utils.infovqa_val_process_results
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
dataset_path: lmms-lab/DocVQA
dataset_name: InfographicVQA
dataset_kwargs:
  token: True
doc_to_target: "answers"
doc_to_visual: !function utils.infovqa_doc_to_visual
doc_to_text: !function utils.infovqa_doc_to_text
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
