dataset_path: ucla-contextual/contextual_val
task: "contextual_val"
test_split: val
output_type: generate_until
doc_to_visual: !function utils.contextual_doc_to_visual
doc_to_text: !function utils.contextual_doc_to_text
doc_to_target: "response"
metric_list:
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0
  
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    pre_prompt: ""
    post_prompt: ""

include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
process_results: !function utils.contextual_process_results