task: "vqav2_valglob"
dataset_kwargs:
  token: True
output_type: generate_until
doc_to_visual: !function utils.vqav2_doc_to_visual
doc_to_text: !function utils.vqav2_doc_to_text
doc_to_target: "answers"
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    pre_prompt: ""
    post_prompt: ""
test_split: validation
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
dataset_path: HuggingFaceM4/VQAv2
fewshot_split: train
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.vqav2_process_results_val
