task: "docvqa_valglob"
test_split: validation
fewshot_split: validation # train
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
dataset_path: lmms-lab/DocVQA
dataset_name: DocVQA
dataset_kwargs:
  token: True
output_type: generate_until
doc_to_visual: !function utils.docvqa_doc_to_visual
doc_to_text: !function utils.docvqa_doc_to_text
doc_to_target: "answers"
process_results: !function utils.docvqa_val_process_results
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    pre_prompt: ""
    post_prompt: ""
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml