task: vizwiz_vqa_valglob
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.vizwiz_vqa_doc_to_visual
doc_to_text: !function utils.vizwiz_vqa_doc_to_text
doc_to_target: "answers"
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    pre_prompt: ""
    post_prompt: ""
process_results: !function utils.vizwiz_vqa_process_results
include: /vqaglob/lmms-eval/lmms_eval/tasks/glob/_default_template_0_yaml
dataset_path: HuggingFaceM4/VizWiz
fewshot_split: train
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: lave
    aggregation: lave
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true